"""Research-only contracts. Live decision modules must not import this package."""
from trading_system.research.information_time import (
    INFORMATION_KEY_VERSION,
    POSITIONAL_ADAPTER_VERSION,
    TIME_INDEXED_ADAPTER_VERSION,
    InformationKey,
    InformationKeyError,
    InformationPhase,
    PositionalTimelineAdapter,
    ResearchInformationTimeError,
    TimeIndexedTimelineAdapter,
    TimelineAdapterError,
    information_time_contract_manifest,
)
from trading_system.research.manifest_identity import (
    ManifestIdentityError,
    validate_feature_manifest_identity,
    validate_narrative_manifest_identity,
)
from trading_system.research.eligibility import (
    ELIGIBILITY_CONTRACT_VERSION,
    EligibilityContractError,
    EligibilityDataError,
    EligibilityError,
    EligibilityReason,
    FactualOutcomeBatch,
    TemporalEligibilityGate,
    TemporalEligibilityResult,
    eligibility_manifest,
)
from trading_system.research.visibility import (
    VISIBILITY_CONTRACT_VERSION,
    AsOfVisibilityProjector,
    FrozenDecisionSnapshotBundle,
    ProjectionContract,
    VisibleAsOfBundle,
    VisibilityError,
    VisibilityProjectionError,
    VisibilitySchemaError,
    visibility_contract_manifest,
)

__all__ = [
    "INFORMATION_KEY_VERSION",
    "POSITIONAL_ADAPTER_VERSION",
    "TIME_INDEXED_ADAPTER_VERSION",
    "VISIBILITY_CONTRACT_VERSION",
    "InformationKey",
    "InformationKeyError",
    "InformationPhase",
    "PositionalTimelineAdapter",
    "TimeIndexedTimelineAdapter",
    "ResearchInformationTimeError",
    "TimelineAdapterError",
    "ManifestIdentityError",
    "validate_feature_manifest_identity",
    "validate_narrative_manifest_identity",
    "ELIGIBILITY_CONTRACT_VERSION",
    "EligibilityContractError",
    "EligibilityDataError",
    "EligibilityError",
    "EligibilityReason",
    "FactualOutcomeBatch",
    "TemporalEligibilityGate",
    "TemporalEligibilityResult",
    "eligibility_manifest",
    "AsOfVisibilityProjector",
    "FrozenDecisionSnapshotBundle",
    "ProjectionContract",
    "VisibleAsOfBundle",
    "VisibilityError",
    "VisibilityProjectionError",
    "VisibilitySchemaError",
    "information_time_contract_manifest",
    "visibility_contract_manifest",
]
