"""MUF V1 S0: market-understanding causal contract foundations.

S0 core contracts only: identity, InformationKey bindings, immutability, and
causal record foundations. S0 does NOT detect or construct market waves and
contains no market semantics, no model/strategy/signal/trade-execution logic,
and no market thresholds or windows.

Public CLOSED contracts reused (never duplicated, never private imports):
- ``trading_system.research.information_time`` (InformationKey semantics)
- ``trading_system.research.hashing`` (canonical_sha256)
- ``trading_system.sources`` (TIE_ORDER_CONTRACT)
"""
from trading_system.market_understanding.availability import (
    AVAILABILITY_SCHEMA_VERSION,
    AvailabilityRule,
    BatchRelation,
    InformationAxis,
    InformationBatchKey,
    InformationKeyBinding,
    MarketChronologyProof,
    SourceBatchIdentity,
    combine_source_batch_status,
    determine_fact_information_key,
    information_batch_relation,
    require_visible_at,
    resolve_batch_order_claim,
)
from trading_system.market_understanding.contracts import (
    S0_CONTRACTS_VERSION,
    S0_ERROR_CLASSES,
    IllegalCausalReference,
    IdentityViolation,
    ImmutabilityViolation,
    IncomparableInformationKeys,
    InformationKeyViolation,
    MufS0ContractError,
    NonEarliestAvailability,
    PrematureAvailability,
    SchemaIdentity,
    SchemaViolation,
    SequenceChronologyViolation,
    TypedState,
    scan_market_shape_implementations,
    scan_private_imports,
    scan_prohibited_implementations,
    typed_state,
)
from trading_system.market_understanding.identity import (
    ARTIFACT_IDENTITY_DOMAIN_ROOT,
    IDENTITY_SCHEMA_VERSION,
    TURNING_POINT_RECORD_TYPE,
    WAVE_PROCESS_FORBIDDEN_IDENTITY_FIELDS,
    WAVE_PROCESS_IDENTITY_DOMAIN,
    WAVE_PROCESS_IDENTITY_FIELDS,
    WAVE_PROCESS_IDENTITY_SCHEMA_VERSION,
    WAVE_PROCESS_SCHEMA,
    ArtifactIdentitySchema,
    AuthoritativeTurningPointReference,
    WaveIdentityProof,
    WaveProcessIdentityBasis,
    canonical_artifact_identity,
    verify_canonical_identity,
    wave_process_identity,
)
from trading_system.market_understanding.records import (
    RECORDS_SCHEMA_VERSION,
    AppendOnlyEventLedger,
    AvailabilityReference,
    CausalRecordReference,
    EventKind,
    EventRecord,
    ImmutableRecord,
    PublishedRecord,
    validate_reference_at,
    validate_reference_type,
)

__all__ = [
    "ARTIFACT_IDENTITY_DOMAIN_ROOT",
    "AVAILABILITY_SCHEMA_VERSION",
    "AppendOnlyEventLedger",
    "ArtifactIdentitySchema",
    "AvailabilityReference",
    "AvailabilityRule",
    "AuthoritativeTurningPointReference",
    "BatchRelation",
    "CausalRecordReference",
    "EventKind",
    "EventRecord",
    "IDENTITY_SCHEMA_VERSION",
    "IllegalCausalReference",
    "IdentityViolation",
    "ImmutabilityViolation",
    "ImmutableRecord",
    "IncomparableInformationKeys",
    "InformationAxis",
    "InformationBatchKey",
    "InformationKeyBinding",
    "InformationKeyViolation",
    "MarketChronologyProof",
    "MufS0ContractError",
    "NonEarliestAvailability",
    "PrematureAvailability",
    "PublishedRecord",
    "RECORDS_SCHEMA_VERSION",
    "S0_CONTRACTS_VERSION",
    "S0_ERROR_CLASSES",
    "SchemaIdentity",
    "SchemaViolation",
    "SequenceChronologyViolation",
    "SourceBatchIdentity",
    "TURNING_POINT_RECORD_TYPE",
    "TypedState",
    "WAVE_PROCESS_FORBIDDEN_IDENTITY_FIELDS",
    "WAVE_PROCESS_IDENTITY_DOMAIN",
    "WAVE_PROCESS_IDENTITY_FIELDS",
    "WAVE_PROCESS_IDENTITY_SCHEMA_VERSION",
    "WAVE_PROCESS_SCHEMA",
    "WaveIdentityProof",
    "WaveProcessIdentityBasis",
    "canonical_artifact_identity",
    "combine_source_batch_status",
    "determine_fact_information_key",
    "information_batch_relation",
    "require_visible_at",
    "resolve_batch_order_claim",
    "scan_market_shape_implementations",
    "scan_private_imports",
    "scan_prohibited_implementations",
    "typed_state",
    "verify_canonical_identity",
    "wave_process_identity",
]
