"""TRAIN-only adaptive calibration research contracts (Module 6.2B-1)."""

from trading_system.calibration.adaptive_confluence import (
    CALIBRATION_CONTRACT_VERSION,
    BaselineRole,
    CalibrationContractError,
    CalibrationDataError,
    CalibrationExperimentSpec,
    CalibrationTrainingInput,
    CalibrationVariantSpec,
    ConfluenceCalibrationArtifact,
    ExperimentAttemptStatus,
    ObjectiveStatus,
    ReasoningTrainingSample,
    WalkForwardAdaptiveConfluenceCalibrationBuilder,
    append_experiment_ledger,
    calibration_contract_manifest,
    experiment_ledger_genesis_hash,
    make_experiment_ledger_entry,
    verify_closed_training_source,
    verify_confluence_calibration_artifact,
)

__all__ = [
    "CALIBRATION_CONTRACT_VERSION",
    "BaselineRole",
    "CalibrationContractError",
    "CalibrationDataError",
    "CalibrationExperimentSpec",
    "CalibrationTrainingInput",
    "CalibrationVariantSpec",
    "ConfluenceCalibrationArtifact",
    "ExperimentAttemptStatus",
    "ObjectiveStatus",
    "ReasoningTrainingSample",
    "WalkForwardAdaptiveConfluenceCalibrationBuilder",
    "append_experiment_ledger",
    "calibration_contract_manifest",
    "experiment_ledger_genesis_hash",
    "make_experiment_ledger_entry",
    "verify_closed_training_source",
    "verify_confluence_calibration_artifact",
]
